### ISSUE TITLE
Stockpred example is confusing

### ISSUE THREAD

**Issue by KansaiUser** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#15]
Related to: [https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/issues/3](https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/issues/3)

I have started reading your book, and I am sorry to say that the explanation is not clear but rather confusing. If in the Chapter01 is like this, I wonder how it would be in more complicated chapters

For example in Chapter 01 you have the stockpred example. 
First the Dockerfile is defective. You forgot the last "\\" in `&& pip install pandas_datareader==0.10.0 \`

Also for the second time you forgot to put the very important final period when you build the image. 

Anyways, the steps to reproduce the problem:
 I build the container with 

`docker build -t stockpred -f Dockerfile .`  (notice the final ".")

and then I had the image.
Next I had to do the `mlflow run .` but you never explained _from where_ did I have to do this. Obviously not from outside the image since mlfow is not installed natively 

so I did

`docker run -v $(pwd):/workfolder -it --rm stockpred
`

Then I am inside the container where mlflow is installed.

So I do
```
> mlflow run .
2022/06/05 08:55:12 ERROR mlflow.cli: === Could not find Docker executable. Ensure Docker is installed as per the instructions at https://docs.docker.com/install/overview/. ===
```
What does this error mean? I mean where do I have to install Docker? _Inside_ the docker image?? (because it is obviously installed natively (since I am using it to build the container images right?)

Please any advice will be welcome.

**Comment by nlauchande** [comment]
Thanks for reporting.
I am working with @emabota to look at the issues at this stage of chapter 1.

**Comment by emabota** [comment]
Hi @KansaiUser, 
**mlflow** must be installed on your local environment through the command `pip install mlflow` as suggested on page 10. 
You shouldn't run `mlflow run .` from inside the container, instead do it from your local environment.

**Comment by nebelgrau77** [comment]
> Hi @KansaiUser, **mlflow** must be installed on your local environment through the command `pip install mlflow` as suggested on page 10. You shouldn't run `mlflow run .` from inside the container, instead do it from your local environment.

A good idea is to create a virtual environment, so that you don't need to add MLflow directly to your main Python installation. Like this:

```bash
virtualenv stockpred_env
source stockpred_env/bin/activate
pip install mlflow==1.27
```
I suggest installing 1.27 as 1.26 causes some problems with... well, Jupyter I believe, but the error messages are quite complex :)

Then inside the virtual environment you can build the container with 

``` bash
docker build -t stockpred -f Dockerfile
```
and then 

```bash
mlflow run .
```

Still inside the virtual environment you can also run 
```bash
mlflow ui
```
and navigate to `http://localhost:5000` in the browser to explore the stored model, metrics etc. 



It is also recommended to cross-check between the book and the Github repo, as the book has some typos and also some incorrect names (e.g. in the book you build a docker image with a tag `stockpred`, but the MLProject file has it as `stockpred-docker`, which of course won't work).

Another important omission in the book is this line in `train.py`:

```python
print(classification_report(y_test, predicted))
```
Without it you will not see the printout shown in the book, just the IDs of the experiment and the message that the run succeeded.

**Comment by webmakaka** [comment]
This issue can be closed, i think.
Thanks to @nebelgrau77

**Comment by KansaiUser** [comment]
Thanks @nebelgrau77
Before I saw your answer, I managed to install mlflow in a virtual environment like
```
python -m venv env
source env/bin/activate
```
I build the docker image and then run 
```
mlflow run .
```
The response to this was quite different than the one in the book but successful it seems. Later with the 
```
mlflow ui
```
I could see the experiments as you said

Thanks again for the clear explanation!

**Comment by nlauchande** [comment]
Closing the issue with an answer from @nebelgrau77.
