### ISSUE TITLE
Chapter 07 - feature store bugged .ipynb 

### ISSUE THREAD

**Issue by hdotking** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#8]
## To reproduce
Follow the instructions on pages 136-137 and run all of the cells in the .ipynb file 

## Bug
This causes an error to arise when creating `training_df` in the .ipynb file.
```
ValueError: Please provide an entity_df with a column named event_timestamp representing the time of events.
```

## Solution
Upon remedying this by changing `"event_date"` in `entity_df` to `"event_timestamp"` the code runs successfully.

However the output is a df with NaN values (see below).

![image](https://user-images.githubusercontent.com/52039339/141168192-5edbd97b-724f-4073-af7f-1facc279dcbd.png)

Is this is the expected output of the code? Have I done something wrong to not have retuned any meaningful data - or is this the expected behaviour?

**Comment by manualrg** [comment]
Hello @hdotking as you said, it is necessary to change to the column name (but also to add some new entities instances),

In add_features.ipynb:

`df['event_timestamp']=df['event_date'].apply(datetime.datetime.fromisoformat)`

In addition, in entities_df, add some examples so that `event_timestamp` can match in join operation:

```
entity_df = pd.DataFrame.from_dict({
    "token": ["btc","btc","btc","btc", "btc", "btc", "btc", "btc"],
    "event_timestamp": [
        datetime(2021, 4, 12, 10, 59, 42),
        datetime(2021, 4, 12, 8,  12, 10),
        datetime(2021, 4, 12, 16, 40, 26),
        datetime(2021, 4, 12, 15, 1 , 12),
        datetime(2021, 6, 26, 11, 8 , 56),
        datetime(2021, 6, 26, 11, 8 , 55),
        datetime(2021, 6, 26, 11, 8 , 55, 222000),
        datetime(2021, 6, 26, 11, 8 , 54)
    ]
})
```

and in register_feature.py 
```
token_features = FileSource(
    path="./data/features.parquet",
    event_timestamp_column="event_timestamp",
    created_timestamp_column="create_date"
)
```
(don't forget to run `feast apply`)


Hope it is useful, just discovering feast and this was not straightforward

![image](https://user-images.githubusercontent.com/30553383/188284861-62729b4a-2bf3-4273-9220-24b4838549ce.png)

**Comment by nlauchande** [comment]
Closing this as it was solved by @manualrg , will consider this if i have a second edition.
